workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      java: 21
    scripts:
      - name: Build Android Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
